name: Test Env Vars

on: [pull_request]

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  test-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          vercel link --yes --token=${{ env.VERCEL_TOKEN }}
          vercel env pull .env.vercel --yes --environment=production --token=${{ env.VERCEL_TOKEN }}

          touch .env
          cat .env.vercel >> .env

      - name: test foo
        run: |
          source .env
          vercel env pull .env.local --yes --environment=production --token=$FOO
